### ISSUE TITLE
Current State?

### ISSUE THREAD

**Issue by diekmann** [frenetic-lang/netkat#2]
What is the state of this repository? Is this project finished? What are the results? What has been verified? Is it just a formalization of the Semantics? Has this repository been abandoned three years ago?

**Comment by jnfoster** [comment]
Hi Cornelius,

Indeed, this repository was essentially abandoned after @cmanderson finished her internship. @smolkaj did another Coq formalization of NetKAT done for a course project but that was also never published. If you're interested in pursuing this, I think it would be great. You should also look at Damien Pous's work. 

Probably we should rename or even delete the repository to indicate that it's not an active project.

-N

**Comment by diekmann** [comment]
Dear Nate,

thanks for the prompt reply and the pointers. I guess just leaving this `issue' open on github indicates the current state of the repository. Please don't delete research artifacts :cold_sweat:

**Comment by jnfoster** [comment]
Indeed, that's why we generally leave things up. But we should update the
README.md and/or maybe have a naming scheme for repositories that are
unmaintained. I have a bunch of tidying to do (on branches and the
organization). I'll get to it eventually...

-N

**Comment by arjunguha** [comment]
You means @canders1?

**Comment by smolkaj** [comment]
popular name, apparently :)
