### ISSUE TITLE
Running an example

### ISSUE THREAD

**Issue by sushiljain1989** [frenetic-lang/netkat#3]
Hi,

Could anyone help me with running an example application (maybe flooding) with netkat ?

~Sushil

**Comment by jnfoster** [comment]
Have you seen the Frenetic Manual?

https://github.com/frenetic-lang/manual/blob/master/programmers_guide/frenetic_programmers_guide.pdf

There are detailed instructions and some suggested exercises there.

If you have seen it, where are you stuck?

-N

**Comment by jnfoster** [comment]
Note that this is a Coq formalization and not the full implementation of NetKAT. That lives in the `frenetic` package.
